# Brewfile

# ------------------------------------------------------------------------
#
# This file is part of tomkyle/dotfiles
# <https://github.com/tomkyle/dotfiles>
#
# ------------------------------------------------------------------------

tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"

brew "nano"
brew "ag"
brew "composer"
